# Generated by Django 5.2.3 on 2025-06-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maslina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('qr_kod', models.CharField(max_length=100, unique=True)),
                ('gps_lat', models.FloatField()),
                ('gps_lon', models.FloatField()),
                ('datum_unosa', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
